#! /usr/bin/env bash
# TODO: Make tasks happen concurrently
# TODO: Save daily output into persistant log

# A script for running daily maintinence tasks.

# Ask for sudo privileges. Required for acts/tarsnap backup
# Don't want to ask for privs lazily, because this should be the sort of thing you
# can walk away from and expect it to be done when you come back.
if [[ $UID != 0 ]]; then # only ask if not already elevated.
  echo "This script requires sudo privileges for backup access."
  sudo echo "Thanks. Commencing dailies."
  # TODO: Should handle rejected sudo request gracefully.
fi

# Check host OS, set $HOST_OS
if [[ "$OSTYPE" == "darwin"* ]]; then
  echo
  echo '---'
  echo 'BREW'
  brew update && brew upgrade && echo 'Update successful.'
elif [[ "$OSTYPE" == "linux-gnu" ]]; then
  echo
  echo '---'
  echo 'APT-GET'
  sudo apt-get update && sudo apt-get upgrade && echo 'Update successful'
else
  echo
  echo '---'
  echo "UNABLE TO DETERMINE HOST OS. CANNOT UPDATE"
fi

#echo
#echo '---'
#echo 'WEATHER'
#curl http://wttr.in/Goleta
#
#
#echo
#echo '---'
#echo 'BACKUP'
#sudo acts && echo 'Backup was successful!'
#
#echo
#echo '---'
#echo 'BUNDLE-AUDIT'
#bundle-audit update
#
#echo
#echo '---'
#echo 'RUBYGEMS'
#gem update --system
#
#echo
#echo '---'
#echo 'TMUX'
#tmux list-sessions
