#! /usr/bin/env bash
# TODO: Make tasks happen concurrently
# TODO: Save daily output into persistant log

# A script for running daily maintinence tasks.

# Ask for sudo privileges. Required for acts/tarsnap backup
# Don't want to ask for privs lazily, because this should be the sort of thing you
# can walk away from and expect it to be done when you come back.
if [[ $UID != 0 ]]; then # only ask if not already elevated.
  echo "This script requires sudo privileges for backup access."
  sudo echo "Thanks. Commencing dailies."
  # TODO: Should handle rejected sudo request gracefully.
fi

echo
echo '---'
echo 'getting weather from wttr.in'
curl http://wttr.in/Goleta

echo
echo '---'
echo 'running brew update, upgrade...'
brew update && brew upgrade && echo 'Update successful.'

echo
echo '---'
echo 'backing up Documents, Projects and bin'
sudo acts && echo 'Backup was successful!'

echo
echo '---'
echo 'updating bundle-audit'
bundle-audit update

echo
echo '---'
echo 'updating gem --system'
gem update --system
