#!/usr/bin/env ruby
# vi: ft=ruby
# vi: spell

# Author: Cooper LeBrun, <cooperlebrun@gmail.com>
# License: MIT (text at the bottom of the file)
# Dependencies: gnuplot, ruby (2+?)

# This program takes a file name, a directory and outputs a file name of a
# graph of flog scores (by class) over time. You can use this with other
# utilities to watch live flog scores over time.

HELP_STRING = <<-EOS
This program takes a file name, a directory and outputs a file name of a graph
of flog scores (by class) over time. You can use this with other utilities to
watch live flog scores over time.

Usage: flog_plot <target> <history_file>
where:

  <target> The file or folder of .rb files you want to flog score.

  <history_file> A gnuplot text file (or empty file) where the old scores will
                 be read in, and the new scores will be appended.
EOS
HELP_STRING.freeze

# I just want to use core right now, so lets use ARGV directly instead of Thor
# or Trollop or something. Probably will replace with the ruby stdlib option
# parser at some point.

# TODO: options
# TODO: make hist file optional, and check in default hist file location.
# TODO: let user specify output filename with option
# TODO: -m, --mutate: append plot commands to hist file

fail ArgumentError, HELP_STRING unless ARGV.size == 2
# TODO: fail if gnuplot not present
# TODO: fail if history_file or target doesn't exist

target       = ARGV[0]
history_file = ARGV[1]

# TODO: Run flog on target

# TODO: parse flog output
  # gnu_plot_text = FlogToGnuplotParser.parse(flog_text)

# TODO: append parser output to history file
  # File.open(history_file, 'a').write(gnu_plot_text)

# TODO: feed history file to gnuplot process. See: https://www.cs.hmc.edu/~vrable/gnuplot/using-gnuplot.html

# TODO: output graph filename/path












# MIT LICENSE TEXT:
# Copyright (c) 2016 Cooper LeBrun

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
