#! /usr/bin/env ruby

raw_hours = File.read(ARGV[0])

times = raw_hours.scan(/Total: \d\d?:\d\d/)

times.map! { |ts| ts.split(' ')[-1] } # Search string -> hours string
times.map! { |hs| hs.split(':').map(&:to_i) } # -> Array of [Hours_int, Minutes_int]

hours = times.map(&:first).reduce(&:+)
minutes = times.map(&:last).reduce(&:+)

# total starting with lowercase t is important, as it won't count again if you tally a file with this text outputted to it
puts "Period total: #{hours + (minutes / 60)}:#{minutes % 60}"
