#! /usr/bin/env ruby
# enter in start time and number of hours you want to add
# output a 24 hour timestamp with a random number of minutes added and a total time length.

HELP_MSG = <<HLP
One argument in the form of start:time/hours_to_add
example: to add 4 hours to 10:15, 10:15/4
HLP

raw_arg = ARGV[0]

hours = raw_arg.split('/')[1].to_i
minutes = (0..59).to_a.sample
start_time = raw_arg.split('/')[0].split(':')

end_time = start_time.map(&:to_i)

# Add time
end_time[1] += minutes
if end_time[1] > 59
  end_time[0] += 1
  end_time[1] -= 60
end
end_time[0] += hours

def clockify(foo)
  foo.to_s.rjust(2, '0')
end

puts " - #{end_time.map { |t| clockify(t) }.join(':')} UTC 2017 | Total: #{clockify(hours)}:#{clockify(minutes)}"
