#!/usr/bin/env bash

# because scaling heroku apps is tooooo haaaaaaaaaarrrrrdduuuuuh

# take a heroku app name and the number of servers you want it to have.
APP_NAME=$1
NUM_OF_SERVS=$2

heroku ps:scale web=$NUM_OF_SERVS --app $APP_NAME
