#! /usr/bin/env bash

# TODO: make port a script argument
# TODO: make channel a script argument
# TODO: y/n dialog to restart localtunnel
# TODO: make y/n restart dialog optional

# run a localtunnel to port 3000, echo the output to the slack channel #dev.
# restart if necessary.

to-slack() {
  slackcat -t -s -p -c dev
}

echo "Press Ctrl-C to exit slacklt."

# exit message
trap '{ echo "Localtunnel url shutting down. Goodbye! :wave:" | to-slack; exit 1; }' INT

echo "Sending localtunnel output to #dev channel"
echo "Starting localtunnel to rails dev server!" | to-slack 

while :
do
  lt -p 3000 | xargs -I message echo 'Rails development server: message' | to-slack
  echo ":boom: Localtunnel has crashed! Restarting." | to-slack
done
