#! /usr/bin/env zsh

# TODO: determine if archive is tar'ed
# tar'ed version of target file/folder name
TAR_GET="$1.tar"

# tar + zstd made easy-er-ish
tar -cvf $TAR_GET $1 && \
  zstd -19 $TAR_GET && \
  rm -ri $TAR_GET $1 && \
  echo "$1 Successfully Compressed."
